var helpers = require('./helpers.ts');
var async = require("async");

exports.version = "0.1.0";

exports.languages = function (req, res) {
  var getp = req.query;

  async.waterfall([
      // get Languages
      function (cb) {

        let len=getp.term.length;
        let results= isoLangs.filter(x => x.name.toLowerCase().substring(0,len)==getp.term);
        // let results= isoLangs.filter(x => x.name.toLowerCase().includes(getp.term));

        cb (null,results.slice(0,5))
      },
  ],
  function (err, languages) {
      if (err) {
        helpers.send_failure(res, helpers.http_code_for_error(err), err);
      } else {
        helpers.send_success(res, languages);
      }
  });
}

// function isCherries(fruit) {
//     return fruit.name === 'cherries';
// }

var isoLangs = [
    {"_id": 0, "name": "Abkhaz", "pic": "0"},
    {"_id": 0, "name": "Afar", "pic": "0"},
    {"_id": 0, "name": "Afrikaans", "pic": "0"},
    {"_id": 0, "name": "Akan", "pic": "0"},
    {"_id": 0, "name": "Albanian", "pic": "0"},
    {"_id": 0, "name": "Amharic", "pic": "0"},
    {"_id": 0, "name": "Arabic", "pic": "0"},
    {"_id": 0, "name": "Aragonese", "pic": "0"},
    {"_id": 0, "name": "Armenian", "pic": "0"},
    {"_id": 0, "name": "Assamese", "pic": "0"},
    {"_id": 0, "name": "Avaric", "pic": "0"},
    {"_id": 0, "name": "Avestan", "pic": "0"},
    {"_id": 0, "name": "Aymara", "pic": "0"},
    {"_id": 0, "name": "Azerbaijani", "pic": "0"},
    {"_id": 0, "name": "Bambara", "pic": "0"},
    {"_id": 0, "name": "Bashkir", "pic": "0"},
    {"_id": 0, "name": "Basque", "pic": "0"},
    {"_id": 0, "name": "Belarusian", "pic": "0"},
    {"_id": 0, "name": "Bengali", "pic": "0"},
    {"_id": 0, "name": "Bihari", "pic": "0"},
    {"_id": 0, "name": "Bislama", "pic": "0"},
    {"_id": 0, "name": "Bosnian", "pic": "0"},
    {"_id": 0, "name": "Breton", "pic": "0"},
    {"_id": 0, "name": "Bulgarian", "pic": "0"},
    {"_id": 0, "name": "Burmese", "pic": "0"},
    {"_id": 0, "name": "Catalan", "pic": "0"},
    {"_id": 0, "name": "Chamorro", "pic": "0"},
    {"_id": 0, "name": "Chechen", "pic": "0"},
    {"_id": 0, "name": "Chichewa", "pic": "0"},
    {"_id": 0, "name": "Chinese", "pic": "0"},
    {"_id": 0, "name": "Chuvash", "pic": "0"},
    {"_id": 0, "name": "Corsican", "pic": "0"},
    {"_id": 0, "name": "Cree", "pic": "0"},
    {"_id": 0, "name": "Croatian", "pic": "0"},
    {"_id": 0, "name": "Czech", "pic": "0"},
    {"_id": 0, "name": "Danish", "pic": "0"},
    {"_id": 0, "name": "Divehi", "pic": "0"},
    {"_id": 0, "name": "Dutch", "pic": "0"},
    {"_id": 0, "name": "English", "pic": "0"},
    {"_id": 0, "name": "Esperanto", "pic": "0"},
    {"_id": 0, "name": "Estonian", "pic": "0"},
    {"_id": 0, "name": "Ewe", "pic": "0"},
    {"_id": 0, "name": "Faroese", "pic": "0"},
    {"_id": 0, "name": "Fijian", "pic": "0"},
    {"_id": 0, "name": "Finnish", "pic": "0"},
    {"_id": 0, "name": "French", "pic": "0"},
    {"_id": 0, "name": "Fula", "pic": "0"},
    {"_id": 0, "name": "Galician", "pic": "0"},
    {"_id": 0, "name": "Georgian", "pic": "0"},
    {"_id": 0, "name": "German", "pic": "0"},
    {"_id": 0, "name": "Greek", "pic": "0"},
    {"_id": 0, "name": "Guaraní", "pic": "0"},
    {"_id": 0, "name": "Gujarati", "pic": "0"},
    {"_id": 0, "name": "Haitian", "pic": "0"},
    {"_id": 0, "name": "Hausa", "pic": "0"},
    {"_id": 0, "name": "Hebrew", "pic": "0"},
    {"_id": 0, "name": "Herero", "pic": "0"},
    {"_id": 0, "name": "Hindi", "pic": "0"},
    {"_id": 0, "name": "Hiri Motu", "pic": "0"},
    {"_id": 0, "name": "Hungarian", "pic": "0"},
    {"_id": 0, "name": "Interlingua", "pic": "0"},
    {"_id": 0, "name": "Indonesian", "pic": "0"},
    {"_id": 0, "name": "Interlingue", "pic": "0"},
    {"_id": 0, "name": "Irish", "pic": "0"},
    {"_id": 0, "name": "Igbo", "pic": "0"},
    {"_id": 0, "name": "Inupiaq", "pic": "0"},
    {"_id": 0, "name": "Ido", "pic": "0"},
    {"_id": 0, "name": "Icelandic", "pic": "0"},
    {"_id": 0, "name": "Italian", "pic": "0"},
    {"_id": 0, "name": "Inuktitut", "pic": "0"},
    {"_id": 0, "name": "Japanese", "pic": "0"},
    {"_id": 0, "name": "Javanese", "pic": "0"},
    {"_id": 0, "name": "Kalaallisut", "pic": "0"},
    {"_id": 0, "name": "Kannada", "pic": "0"},
    {"_id": 0, "name": "Kanuri", "pic": "0"},
    {"_id": 0, "name": "Kashmiri", "pic": "0"},
    {"_id": 0, "name": "Kazakh", "pic": "0"},
    {"_id": 0, "name": "Khmer", "pic": "0"},
    {"_id": 0, "name": "Kikuyu", "pic": "0"},
    {"_id": 0, "name": "Kinyarwanda", "pic": "0"},
    {"_id": 0, "name": "Kirghiz", "pic": "0"},
    {"_id": 0, "name": "Komi", "pic": "0"},
    {"_id": 0, "name": "Kongo", "pic": "0"},
    {"_id": 0, "name": "Korean", "pic": "0"},
    {"_id": 0, "name": "Kurdish", "pic": "0"},
    {"_id": 0, "name": "Kwanyama", "pic": "0"},
    {"_id": 0, "name": "Latin", "pic": "0"},
    {"_id": 0, "name": "Luxembourgish", "pic": "0"},
    {"_id": 0, "name": "Luganda", "pic": "0"},
    {"_id": 0, "name": "Limburgish", "pic": "0"},
    {"_id": 0, "name": "Lingala", "pic": "0"},
    {"_id": 0, "name": "Lao", "pic": "0"},
    {"_id": 0, "name": "Lithuanian", "pic": "0"},
    {"_id": 0, "name": "Luba-Katanga", "pic": "0"},
    {"_id": 0, "name": "Latvian", "pic": "0"},
    {"_id": 0, "name": "Manx", "pic": "0"},
    {"_id": 0, "name": "Macedonian", "pic": "0"},
    {"_id": 0, "name": "Malagasy", "pic": "0"},
    {"_id": 0, "name": "Malay", "pic": "0"},
    {"_id": 0, "name": "Malayalam", "pic": "0"},
    {"_id": 0, "name": "Maltese", "pic": "0"},
    {"_id": 0, "name": "Māori", "pic": "0"},
    {"_id": 0, "name": "Marathi", "pic": "0"},
    {"_id": 0, "name": "Marshallese", "pic": "0"},
    {"_id": 0, "name": "Mongolian", "pic": "0"},
    {"_id": 0, "name": "Nauru", "pic": "0"},
    {"_id": 0, "name": "Norwegian Bokmål", "pic": "0"},
    {"_id": 0, "name": "North Ndebele", "pic": "0"},
    {"_id": 0, "name": "Nepali", "pic": "0"},
    {"_id": 0, "name": "Ndonga", "pic": "0"},
    {"_id": 0, "name": "Norwegian Nynorsk", "pic": "0"},
    {"_id": 0, "name": "Norwegian", "pic": "0"},
    {"_id": 0, "name": "Nuosu", "pic": "0"},
    {"_id": 0, "name": "South Ndebele", "pic": "0"},
    {"_id": 0, "name": "Occitan", "pic": "0"},
    {"_id": 0, "name": "Ojibwe", "pic": "0"},
    {"_id": 0, "name": "Old Church Slavonic", "pic": "0"},
    {"_id": 0, "name": "Oromo", "pic": "0"},
    {"_id": 0, "name": "Oriya", "pic": "0"},
    {"_id": 0, "name": "Ossetian", "pic": "0"},
    {"_id": 0, "name": "Panjabi", "pic": "0"},
    {"_id": 0, "name": "Pāli", "pic": "0"},
    {"_id": 0, "name": "Persian", "pic": "0"},
    {"_id": 0, "name": "Polish", "pic": "0"},
    {"_id": 0, "name": "Pashto", "pic": "0"},
    {"_id": 0, "name": "Portuguese", "pic": "0"},
    {"_id": 0, "name": "Quechua", "pic": "0"},
    {"_id": 0, "name": "Romansh", "pic": "0"},
    {"_id": 0, "name": "Kirundi", "pic": "0"},
    {"_id": 0, "name": "Romanian", "pic": "0"},
    {"_id": 0, "name": "Russian", "pic": "0"},
    {"_id": 0, "name": "Sanskrit", "pic": "0"},
    {"_id": 0, "name": "Sardinian", "pic": "0"},
    {"_id": 0, "name": "Sindhi", "pic": "0"},
    {"_id": 0, "name": "Northern Sami", "pic": "0"},
    {"_id": 0, "name": "Samoan", "pic": "0"},
    {"_id": 0, "name": "Sango", "pic": "0"},
    {"_id": 0, "name": "Serbian", "pic": "0"},
    {"_id": 0, "name": "Scottish Gaelic", "pic": "0"},
    {"_id": 0, "name": "Shona", "pic": "0"},
    {"_id": 0, "name": "Sinhala", "pic": "0"},
    {"_id": 0, "name": "Slovak", "pic": "0"},
    {"_id": 0, "name": "Slovene", "pic": "0"},
    {"_id": 0, "name": "Somali", "pic": "0"},
    {"_id": 0, "name": "Southern Sotho", "pic": "0"},
    {"_id": 0, "name": "Spanish", "pic": "0"},
    {"_id": 0, "name": "Sundanese", "pic": "0"},
    {"_id": 0, "name": "Swahili", "pic": "0"},
    {"_id": 0, "name": "Swati", "pic": "0"},
    {"_id": 0, "name": "Swedish", "pic": "0"},
    {"_id": 0, "name": "Tamil", "pic": "0"},
    {"_id": 0, "name": "Telugu", "pic": "0"},
    {"_id": 0, "name": "Tajik", "pic": "0"},
    {"_id": 0, "name": "Thai", "pic": "0"},
    {"_id": 0, "name": "Tigrinya", "pic": "0"},
    {"_id": 0, "name": "Tibetan Standard", "pic": "0"},
    {"_id": 0, "name": "Turkmen", "pic": "0"},
    {"_id": 0, "name": "Tagalog", "pic": "0"},
    {"_id": 0, "name": "Tswana", "pic": "0"},
    {"_id": 0, "name": "Tonga", "pic": "0"},
    {"_id": 0, "name": "Turkish", "pic": "0"},
    {"_id": 0, "name": "Tsonga", "pic": "0"},
    {"_id": 0, "name": "Tatar", "pic": "0"},
    {"_id": 0, "name": "Twi", "pic": "0"},
    {"_id": 0, "name": "Tahitian", "pic": "0"},
    {"_id": 0, "name": "Uighur", "pic": "0"},
    {"_id": 0, "name": "Ukrainian", "pic": "0"},
    {"_id": 0, "name": "Urdu", "pic": "0"},
    {"_id": 0, "name": "Uzbek", "pic": "0"},
    {"_id": 0, "name": "Venda", "pic": "0"},
    {"_id": 0, "name": "Vietnamese", "pic": "0"},
    {"_id": 0, "name": "Volapük", "pic": "0"},
    {"_id": 0, "name": "Walloon", "pic": "0"},
    {"_id": 0, "name": "Welsh", "pic": "0"},
    {"_id": 0, "name": "Wolof", "pic": "0"},
    {"_id": 0, "name": "Western Frisian", "pic": "0"},
    {"_id": 0, "name": "Xhosa", "pic": "0"},
    {"_id": 0, "name": "Yiddish", "pic": "0"},
    {"_id": 0, "name": "Yoruba", "pic": "0"},
    {"_id": 0, "name": "Zhuang", "pic": "0"},
];
