export { objectMini,
         objectMiniEmail,
         objectMiniPosition,
         groupComplex,
         complexName,
         Period,
         Analytics,
         Quote,
         Affiliation,
         SocialInfo,
         PublicInfo,
         Rank,
         Link
       };

interface objectMini {
  _id: string,
  name: string,
  pic: string
}

interface objectMiniEmail {
  _id: string,
  name: string,
  pic: string,
  email: string,
  message: string,
  dates: Date[]
}

interface objectMiniPosition {
  _id: string,
  name: string,
  pic: string,
  email: string,
  position: number,
  startDate: Date,
  endDate: Date,
  active: boolean[],
  message: string,
  messageFlag: boolean[],
}


interface groupComplex {
  group: complexName,
  department: complexName,
  university: complexName
}

interface complexName {
  _id: string,
  name: string,
  pic: string,
  link: string
}

interface Period {
  start: Date,
  end: Date,
  mode: number // 0 - stard-end, 1 - start-present, 2 - start
}

interface Analytics {
  id: number,
  name: string,
  views: number[],
  secondary: number[],
}

interface Quote {
  text: string,
  name: string,
  pic: string
}

interface Affiliation {
  _id: string,
  title: string,
  abbr: string,
  description: string,
  source: string,
  externalLink: string,
  pic: string
}

interface SocialInfo {
  linkedin: string,
  twitter: string,
  scholar: string,
  orcid: string,
  github: string,
  researchgate: string,
  facebook: string,
  youtube: string,
  pinterest: string,
  instagram: string
}

interface PublicInfo {
  address: string,
  email: string,
  phone: string,
  fax: string,
  website: string
}

interface Rank {
  times: number,
  shanghai: number,
  top: number,
  usnews: number,
  facebook: number,
  twitter: number,
  linkedin: number,
  instagram: number,
  youtube: number
}

interface Link {
    _id: string,
    name: string,
    link: string,
    description: string
}

export let Countries = [
  { "id": 0,   "name": "Academig World", "code": "0" },
  { "id": 4,   "name": "Afghanistan", "code": "AF" },
  { "id": 248, "name": "Aland Islands", "code": "0" },
  { "id": 8,   "name": "Albania", "code": "AL" },
  { "id": 12,  "name": "Algeria", "code": "DZ" },
  { "id": 16,  "name": "American Samoa", "code": "0" },
  { "id": 20,  "name": "Andorra", "code": "0" },
  { "id": 24,  "name": "Angola", "code": "AO" },
  { "id": 660, "name": "Anguilla", "code": "0" },
  { "id": 10,  "name": "Antarctica", "code": "0" },
  { "id": 28,  "name": "Antigua and Barbuda", "code": "0" },
  { "id": 32,  "name": "Argentina", "code": "AR" },
  { "id": 51,  "name": "Armenia", "code": "AM" },
  { "id": 533, "name": "Aruba", "code": "0" },
  { "id": 36,  "name": "Australia", "code": "AU" },
  { "id": 40,  "name": "Austria", "code": "AT" },
  { "id": 31,  "name": "Azerbaijan", "code": "AZ" },
  { "id": 44,  "name": "Bahamas", "code": "BS" },
  { "id": 48,  "name": "Bahrain", "code": "0" },
  { "id": 50,  "name": "Bangladesh", "code": "BD" },
  { "id": 52,  "name": "Barbados", "code": "0" },
  { "id": 112, "name": "Belarus", "code": "BY" },
  { "id": 56,  "name": "Belgium", "code": "BE" },
  { "id": 84,  "name": "Belize", "code": "BZ" },
  { "id": 204, "name": "Benin", "code": "BJ" },
  { "id": 60,  "name": "Bermuda", "code": "0" },
  { "id": 64,  "name": "Bhutan", "code": "BT" },
  { "id": 68,  "name": "Bolivia", "code": "BO" },
  { "id": 70,  "name": "Bosnia and Herz.", "code": "BA" },
  { "id": 72,  "name": "Botswana", "code": "BW" },
  { "id": 74,  "name": "Bouvet Island", "code": "0" },
  { "id": 76,  "name": "Brazil", "code": "BR" },
  { "id": 86,  "name": "British Indian Ocean Territory", "code": "0" },
  { "id": 96,  "name": "Brunei", "code": "BN" },
  { "id": 100, "name": "Bulgaria", "code": "BG" },
  { "id": 854, "name": "Burkina Faso", "code": "BF" },
  { "id": 108, "name": "Burundi", "code": "BI" },
  { "id": 116, "name": "Cambodia", "code": "KH" },
  { "id": 120, "name": "Cameroon", "code": "CM" },
  { "id": 124, "name": "Canada", "code": "CA" },
  { "id": 132, "name": "Cape Verde", "code": "0" },
  { "id": 136, "name": "Cayman Islands", "code": "0"},
  { "id": 140, "name": "Central African Republic", "code": "CF" },
  { "id": 148, "name": "Chad", "code": "TD"},
  { "id": 152, "name": "Chile", "code": "CL"},
  { "id": 156, "name": "China", "code": "CN"},
  { "id": 162, "name": "Christmas Island", "code": "0"},
  { "id": 170, "name": "Colombia", "code": "CO"},
  { "id": 174, "name": "Comoros", "code": "0"},
  { "id": 178, "name": "Congo", "code": "CG"},
  { "id": 184, "name": "Cook Islands"},
  { "id": 188, "name": "Costa Rica", "code": "CR" },
  { "id": 191, "name": "Croatia", "code": "HR" },
  { "id": 192, "name": "Cuba", "code": "CU" },
  { "id": 196, "name": "Cyprus", "code": "CY" },
  { "id": 203, "name": "Czech Rep.", "code": "CZ" },
  { "id": 208, "name": "Denmark", "code": "DK" },
  { "id": 262, "name": "Djibouti", "code": "DJ" },
  { "id": 212, "name": "Dominica", "code": "0" },
  { "id": 214, "name": "Dominican Rep.", "code": "DO"},
  { "id": 218, "name": "Ecuador", "code": "EC" },
  { "id": 818, "name": "Egypt", "code": "EG" },
  { "id": 222, "name": "El Salvador", "code": "SV" },
  { "id": 226, "name": "Eq. Guinea", "code": "GQ" },
  { "id": 232, "name": "Eritrea", "code": "ER" },
  { "id": 233, "name": "Estonia", "code": "EE" },
  { "id": 231, "name": "Ethiopia", "code": "ET" },
  { "id": 234, "name": "Faroe Islands", "code": "" },
  { "id": 242, "name": "Fiji", "code": "FJ" },
  { "id": 246, "name": "Finland", "code": "FI" },
  { "id": 250, "name": "France", "code": "FR" },
  { "id": 254, "name": "French Guiana", "code": "" },
  { "id": 258, "name": "French Polynesia", "code": "" },
  { "id": 260, "name": "French Southern Territories", "code": "" },
  { "id": 266, "name": "Gabon", "code": "GA" },
  { "id": 270, "name": "Gambia", "code": "GM" },
  { "id": 268, "name": "Georgia", "code": "GE" },
  { "id": 276, "name": "Germany", "code": "DE" },
  { "id": 288, "name": "Ghana", "code": "GH" },
  { "id": 292, "name": "Gibraltar", "code": "" },
  { "id": 300, "name": "Greece", "code": "GR" },
  { "id": 304, "name": "Greenland", "code": "GL" },
  { "id": 308, "name": "Grenada", "code": "" },
  { "id": 312, "name": "Guadeloupe", "code": "" },
  { "id": 316, "name": "Guam", "code": "" },
  { "id": 320, "name": "Guatemala", "code": "GT" },
  { "id": 831, "name": "Guernsey", "code": "" },
  { "id": 324, "name": "Guinea", "code": "GN" },
  { "id": 624, "name": "Guinea-Bissau", "code": "GW" },
  { "id": 328, "name": "Guyana", "code": "GY" },
  { "id": 332, "name": "Haiti", "code": "HT" },
  { "id": 340, "name": "Honduras", "code": "HN" },
  { "id": 344, "name": "Hong Kong", "code": "" },
  { "id": 348, "name": "Hungary", "code": "HU" },
  { "id": 352, "name": "Iceland", "code": "IS" },
  { "id": 356, "name": "India", "code": "IN" },
  { "id": 360, "name": "Indonesia", "code": "ID" },
  { "id": 364, "name": "Iran", "code": "IR" },
  { "id": 368, "name": "Iraq", "code": "IQ" },
  { "id": 372, "name": "Ireland", "code": "IE" },
  { "id": 833, "name": "Isle of Man", "code": "" },
  { "id": 376, "name": "Israel", "code": "IL" },
  { "id": 380, "name": "Italy", "code": "IT" },
  { "id": 388, "name": "Jamaica", "code": "JM" },
  { "id": 392, "name": "Japan", "code": "JP" },
  { "id": 832, "name": "Jersey", "code": ""},
  { "id": 400, "name": "Jordan", "code": "JO" },
  { "id": 398, "name": "Kazakhstan", "code": "KZ" },
  { "id": 404, "name": "Kenya", "code": "KE" },
  { "id": 296, "name": "Kiribati", "code": ""},
  { "id": 414, "name": "Kuwait", "code": "KW" },
  { "id": 417, "name": "Kyrgyzstan", "code": "KG" },
  { "id": 428, "name": "Latvia", "code": "LV" },
  { "id": 422, "name": "Lebanon", "code": "LB" },
  { "id": 426, "name": "Lesotho", "code": "LS" },
  { "id": 430, "name": "Liberia", "code": "LR" },
  { "id": 434, "name": "Libya", "code": "LY" },
  { "id": 438, "name": "Liechtenstein", "code": "" },
  { "id": 440, "name": "Lithuania", "code": "LT" },
  { "id": 442, "name": "Luxembourg", "code": "LU" },
  { "id": 446, "name": "Macao", "code": "" },
  { "id": 807, "name": "Macedonia", "code": "MK" },
  { "id": 450, "name": "Madagascar", "code": "MG" },
  { "id": 454, "name": "Malawi", "code": "MW" },
  { "id": 458, "name": "Malaysia", "code": "MY" },
  { "id": 462, "name": "Maldives", "code": "" },
  { "id": 466, "name": "Mali", "code": "ML" },
  { "id": 470, "name": "Malta", "code": "" },
  { "id": 584, "name": "Marshall Islands"},
  { "id": 474, "name": "Martinique", "code": "" },
  { "id": 478, "name": "Mauritania", "code": "MR" },
  { "id": 480, "name": "Mauritius", "code": "" },
  { "id": 175, "name": "Mayotte", "code": "" },
  { "id": 484, "name": "Mexico", "code": "MX" },
  { "id": 583, "name": "Micronesia"},
  { "id": 498, "name": "Moldova", "code": "MD" },
  { "id": 492, "name": "Monaco", "code": "" },
  { "id": 496, "name": "Mongolia", "code": "MN" },
  { "id": 499, "name": "Montenegro", "code": "ME" },
  { "id": 500, "name": "Montserrat", "code": "" },
  { "id": 504, "name": "Morocco", "code": "MA" },
  { "id": 508, "name": "Mozambique", "code": "MZ" },
  { "id": 104, "name": "Myanmar", "code": "MM" },
  { "id": 516, "name": "Namibia", "code": "NA" },
  { "id": 520, "name": "Nauru", "code": "" },
  { "id": 524, "name": "Nepal", "code": "97" },
  { "id": 528, "name": "Netherlands", "code": "89" },
  { "id": 540, "name": "New Caledonia", "code": "93" },
  { "id": 554, "name": "New Zealand", "code": "96" },
  { "id": 558, "name": "Nicaragua", "code": "88" },
  { "id": 562, "name": "Niger", "code": "94" },
  { "id": 566, "name": "Nigeria", "code": "95" },
  { "id": 570, "name": "Niue", "code": "" },
  { "id": 574, "name": "Norfolk Island", "code": "NI" },
  { "id": 410, "name": "North Korea", "code": "NK" },
  { "id": 580, "name": "Northern Mariana Islands"},
  { "id": 578, "name": "Norway", "code": "NO" },
  { "id": 512, "name": "Oman", "code": "OM" },
  { "id": 586, "name": "Pakistan", "code": "PK" },
  { "id": 585, "name": "Palau", "code": "" },
  { "id": 275, "name": "Palestine", "code": "PS"},
  { "id": 591, "name": "Panama", "code": "PA" },
  { "id": 598, "name": "Papua New Guinea", "code": "PG" },
  { "id": 600, "name": "Paraguay", "code": "PY" },
  { "id": 604, "name": "Peru", "code": "PE" },
  { "id": 608, "name": "Philippines", "code": "PH" },
  { "id": 612, "name": "Pitcairn", "code": "" },
  { "id": 616, "name": "Poland", "code": "PL" },
  { "id": 620, "name": "Portugal", "code": "PT" },
  { "id": 630, "name": "Puerto Rico", "code": "PR" },
  { "id": 634, "name": "Qatar", "code": "QA"},
  { "id": 638, "name": "Réunion", "code": "" },
  { "id": 642, "name": "Romania", "code": "RO" },
  { "id": 643, "name": "Russian Federation", "code": "RU" },
  { "id": 646, "name": "Rwanda", "code": "RW" },
  { "id": 659, "name": "Saint Kitts and Nevis"},
  { "id": 670, "name": "Saint Vincent and the Grenadines"},
  { "id": 882, "name": "Samoa", "code": "" },
  { "id": 674, "name": "San Marino", "code": "" },
  { "id": 678, "name": "Sao Tome and Principe"},
  { "id": 682, "name": "Saudi Arabia", "code": "SA" },
  { "id": 686, "name": "Senegal", "code": "SN" },
  { "id": 688, "name": "Serbia", "code": "RS" },
  { "id": 690, "name": "Seychelles", "code": "" },
  { "id": 694, "name": "Sierra Leone", "code": "SL" },
  { "id": 702, "name": "Singapore", "code": "" },
  { "id": 703, "name": "Slovakia", "code": "SK" },
  { "id": 705, "name": "Slovenia", "code": "SI" },
  { "id": 90,  "name": "Solomon Is.", "code": "SB" },
  { "id": 706, "name": "Somalia", "code": "SO" },
  { "id": 710, "name": "South Africa", "code": "ZA" },
  { "id": 239, "name": "South Georgia and the South Sandwich Islands"},
  { "id": 410, "name": "South Korea", "code": "KR" },
  { "id": 724, "name": "Spain", "code": "ES" },
  { "id": 144, "name": "Sri Lanka", "code": "LK" },
  { "id": 736, "name": "Sudan", "code": "SD" },
  { "id": 740, "name": "Suriname", "code": "SR" },
  { "id": 744, "name": "Svalbard and Jan Mayen"},
  { "id": 748, "name": "Swaziland", "code": "SZ" },
  { "id": 752, "name": "Sweden", "code": "SE" },
  { "id": 756, "name": "Switzerland", "code": "CH" },
  { "id": 760, "name": "Syria", "code": "SY" },
  { "id": 158, "name": "Taiwan", "code": "TW" },
  { "id": 762, "name": "Tajikistan", "code": "TJ" },
  { "id": 834, "name": "Tanzania", "code": "TZ" },
  { "id": 764, "name": "Thailand", "code": "TH" },
  { "id": 626, "name": "Timor-Leste", "code": "TL" },
  { "id": 768, "name": "Togo", "code": "TG" },
  { "id": 772, "name": "Tokelau", "code": "" },
  { "id": 776, "name": "Tonga", "code": "" },
  { "id": 780, "name": "Trinidad and Tobago", "code": "TT" },
  { "id": 788, "name": "Tunisia", "code": "TN" },
  { "id": 792, "name": "Turkey", "code": "TR" },
  { "id": 795, "name": "Turkmenistan", "code": "TM" },
  { "id": 796, "name": "Turks and Caicos Islands"},
  { "id": 798, "name": "Tuvalu", "code": "" },
  { "id": 800, "name": "Uganda", "code": "UG" },
  { "id": 804, "name": "Ukraine", "code": "UA" },
  { "id": 784, "name": "United Arab Emirates", "code": "AE" },
  { "id": 826, "name": "United Kingdom", "code": "GB" },
  { "id": 840, "name": "United States of America", "code": "US"},
  { "id": 858, "name": "Uruguay", "code": "UY" },
  { "id": 860, "name": "Uzbekistan", "code": "UZ" },
  { "id": 548, "name": "Vanuatu", "code": "VU" },
  { "id": 862, "name": "Venezuela", "code": "VE" },
  { "id": 704, "name": "Vietnam", "code": "VN" },
  { "id": 92,  "name": "Virgin Islands, British", "code": "" },
  { "id": 850, "name": "Virgin Islands, U.S.", "code": "" },
  { "id": 876, "name": "Wallis and Futuna", "code": "" },
  { "id": 732, "name": "W. Sahara", "code": "EH" },
  { "id": 887, "name": "Yemen", "code": "YE" },
  { "id": 894, "name": "Zambia", "code": "ZM" },
  { "id": 716, "name": "Zimbabwe", "code": "ZW" }
]
